# Generated by Django 3.2.5 on 2021-07-15 20:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('background', models.CharField(max_length=150, verbose_name='Formação')),
                ('bio', ckeditor.fields.RichTextField(verbose_name='Biográfia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
