# Generated by Django 3.2.5 on 2021-07-15 20:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('short_description', models.CharField(max_length=160, verbose_name='Descrição curta')),
                ('author', models.CharField(max_length=150, verbose_name='Criado por')),
                ('price', models.DecimalField(decimal_places=2, help_text='Informe o valor sem o símbolo da moeda.', max_digits=19, verbose_name='Preço')),
                ('what_learn', ckeditor.fields.RichTextField(verbose_name='O que você vai aprender')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Requisitos')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('for_what', ckeditor.fields.RichTextField(verbose_name='Pra quem é este curso')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagem do curso')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
