# Generated by Django 3.2.5 on 2021-07-15 20:46

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Somente cursos ativos serão visíveis.', verbose_name='Curso Ativo?'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, help_text='Preenchimento automático', populate_from='name', unique=True, verbose_name='URL Única'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
