# Generated by Django 3.2.5 on 2021-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210715_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(default='', verbose_name='Link de Compra'),
            preserve_default=False,
        ),
    ]
