# Generated by Django 3.2.5 on 2021-09-06 02:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Hotmart, Monetizze', max_length=150, verbose_name='Plataforma')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Preencimento automático', populate_from='name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
    ]
