# Generated by Django 3.2.5 on 2021-09-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.platform', verbose_name='Plataforma'),
        ),
    ]
