# Generated by Django 3.2.5 on 2021-09-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Tente criar um título de 60 caracteres no máximo.', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(help_text='Tente criar uma descrição de até 160 caracteres.', max_length=160, verbose_name='Descrição curta'),
        ),
    ]
