# Generated by Django 3.2.5 on 2021-11-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_teacher_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='background',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Formação'),
        ),
    ]
