# Generated by Django 3.2.5 on 2021-11-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_teacher_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
    ]
