# Generated by Django 3.2.5 on 2021-11-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='for_what',
        ),
    ]
