# Generated by Django 3.2.5 on 2021-11-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_for_what'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='what_learn',
        ),
    ]
