# Generated by Django 3.2.5 on 2022-01-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(default='', help_text='Separadas por virgula', max_length=255, verbose_name='Palavras chaves'),
        ),
    ]
