# Generated by Django 3.2.5 on 2023-01-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20230107_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.platform', verbose_name='Plataforma'),
        ),
    ]
