# Generated by Django 3.2.5 on 2023-01-08 19:55

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tente criar um título de 60 caracteres no máximo.', max_length=100, verbose_name='Nome')),
                ('short_description', models.CharField(help_text='Tente criar uma descrição de até 160 caracteres.', max_length=160, verbose_name='Descrição curta')),
                ('keywords', models.CharField(default='', help_text='Separadas por virgula', max_length=255, verbose_name='Palavras chaves')),
                ('url', models.URLField(verbose_name='Link de Download')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='images', verbose_name='Imagem do curso')),
                ('is_active', models.BooleanField(default=True, help_text='Somente cursos ativos serão visíveis.', verbose_name='Curso Ativo?')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Preenchimento automático', populate_from='name', unique=True, verbose_name='URL Única')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Material Gratuito',
                'verbose_name_plural': 'Material Gratuito',
            },
        ),
    ]
