# Generated by Django 3.2.5 on 2023-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_materialfree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfree',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Imagem do material'),
        ),
        migrations.AlterField(
            model_name='materialfree',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Somente materiais ativos serão visíveis.', verbose_name='Material Ativo?'),
        ),
    ]
