# Generated by Django 3.2.5 on 2021-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', help_text='Imagem de capa do post', upload_to='images', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
