# Generated by Django 3.2.5 on 2021-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default='teste', help_text='Uma pequena descrição do texto, será usada também para o SEO.', max_length=160, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
    ]
