# Generated by Django 3.2.5 on 2022-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta descrição')),
                ('meta_keywords', models.CharField(max_length=255, verbose_name='Meta keywords')),
            ],
            options={
                'verbose_name': 'SEO Home',
                'verbose_name_plural': 'SEO Home',
            },
        ),
    ]
