# Generated by Django 3.2.5 on 2022-01-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_seohome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seohome',
            name='meta_keywords',
            field=models.CharField(help_text='Separadas por virgula', max_length=255, verbose_name='Palavras chaves'),
        ),
    ]
