# Generated by Django 3.2.5 on 2022-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_alter_seohome_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_id', models.CharField(max_length=75, verbose_name='Código GA')),
            ],
            options={
                'verbose_name': 'Google Analytics',
                'verbose_name_plural': 'Google Analytics',
            },
        ),
    ]
