# Generated by Django 3.2.5 on 2022-01-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_googleanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nome do Script')),
                ('script', models.TextField(help_text='Adicione o script completo, inclusive com as tags <script></script>.', verbose_name='Script')),
                ('place', models.CharField(choices=[('HD', 'Head/Cabeçalho'), ('FT', 'Footer/Rodapé')], help_text='Escolha onde o script deve ser inserido.', max_length=2, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
            },
        ),
    ]
