# Generated by Django 3.2.5 on 2022-01-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Os scripts inativos deixarão de ser inseridos nas páginas.', verbose_name='Ativo?'),
        ),
    ]
