# Generated by Django 3.2.5 on 2021-07-15 12:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text_page',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
    ]
