# Generated by Django 3.2.5 on 2021-08-14 21:21

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_aboutus_text_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('short_description', models.CharField(max_length=160, verbose_name='Descrição curta')),
                ('text', models.TextField(help_text='Escreva um texto sobre o vídeo', verbose_name='Texto')),
                ('url', models.URLField(help_text='Insira a URL do vídeo no YouTube', verbose_name='URL')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='Thumbnail')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Preenchimento automático', populate_from='title', unique=True, verbose_name='URL única')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cirado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
    ]
