# Generated by Django 3.2.5 on 2021-08-14 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Escreva um texto sobre o vídeo', verbose_name='Texto'),
        ),
    ]
