# Generated by Django 3.2.5 on 2021-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210909_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.PositiveBigIntegerField(choices=[(1, 'Instagram'), (2, 'Facebook'), (3, 'YouTube'), (4, 'Linkedin'), (5, 'Twitter')], verbose_name='Rede Social')),
                ('profile_url', models.URLField(help_text='Ex: https://instagram.com/martaconcurseira', verbose_name='URL do perfil')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
    ]
