# Generated by Django 3.2.5 on 2021-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.PositiveBigIntegerField(choices=[(1, 'Bloco 1'), (2, 'Bloco 2'), (3, 'Bloco 3')], verbose_name='Bloco')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='Imagem')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['block'],
            },
        ),
    ]
