# Generated by Django 3.2.5 on 2021-11-02 21:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
