# Generated by Django 3.2.5 on 2023-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FilePathField(max_length=255, path='/')),
            ],
        ),
    ]
