# Generated by Django 3.2.5 on 2023-09-27 04:15

import django.core.validators
from django.db import migrations, models
import sitemap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to=sitemap.models.upload_to_static, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml']), sitemap.models.validate_xml_extension])),
            ],
        ),
    ]
